TEAMS_SOFASCORE = {
    "Argentina": 4819,
    "Brazil": 4748,
    "France": 4481,
    "England": 4713,
    "Spain": 4698,
    "Germany": 4711,
    "Portugal": 4704,
    "Netherlands": 4705,
    "Italy": 4707,
    "Belgium": 4717,
    "Croatia": 4715,
    "Uruguay": 4725,
    "Colombia": 4820,
    "Morocco": 4778,
    "Japan": 4770,
    "Mexico": 4781,
    "USA": 4724,
    "Denmark": 4476,
    "Switzerland": 4699,
    "Austria": 4718,
    "Serbia": 6355,
    "Ukraine": 4701,
    "Poland": 4703,
    "Sweden": 4688,
    "Norway": 4475,
    "South Korea": 4735,
    "Senegal": 4739,
    "Nigeria": 4785,
    "Ecuador": 4757,
}

TEAMS_FLAG_CODES = {
    "Argentina": "ar",
    "Brazil": "br",
    "France": "fr",
    "England": "gb-eng",
    "Spain": "es",
    "Germany": "de",
    "Portugal": "pt",
    "Netherlands": "nl",
    "Italy": "it",
    "Belgium": "be",
    "Croatia": "hr",
    "Uruguay": "uy",
    "Colombia": "co",
    "Morocco": "ma",
    "Japan": "jp",
    "Mexico": "mx",
    "USA": "us",
    "Denmark": "dk",
    "Switzerland": "ch",
    "Austria": "at",
    "Serbia": "rs",
    "Ukraine": "ua",
    "Poland": "pl",
    "Sweden": "se",
    "Norway": "no",
    "South Korea": "kr",
    "Senegal": "sn",
    "Nigeria": "ng",
    "Ecuador": "ec",
}
